# .NET Core NuGet Package
# Build and publish .NET Core NuGet package projects

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  publishProject: 'ReactiveComponentModel.csproj'
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: recursive

- task: UseDotNet@2
  displayName: 'Use .NET Core 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    arguments: '-c $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
#    packagesToPack: '$(publishProject)'

- task: DotNetCoreCLI@2
  displayName: Push
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGet'
