# .NET Core NuGet Package
# Build and publish .NET Core NuGet package projects

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- checkout: self
  submodules: recursive

- task: UseDotNet@2
  displayName: 'Use .NET Core 3.x'
  inputs:
    version: 3.x
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    arguments: '-c $(BuildConfiguration) -o $(Build.ArtifactStagingDirectory)'
